service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: femasters
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:  
  api:
    handler: src/api/api.handler
    events:
      - http: 
          path: /api
          method: GET
          cors: true
  todos:
    handler: src/api/todos.handler
    events:
      - http: 
          path: /todo/{id}
          method: GET
          parameters: 
            id: true
          
  todo:
    handler: src/api/todo.handler
    
